const $=s=>document.querySelector(s);
let stream=null, scanTimer=null, analysisTimer=null, model=null, requestId=0;
const foods={
  tomato:{name:'помидор',title:'Кажется,<br>у нас томатч!',mood:'Проверь меня: я ещё могу перепутать',kcal:'18',protein:'0,9 г',fat:'0,2 г',carbs:'3,9 г',fiber:'1,2 г',advice:'Томат ищет компанию',text:'Добавь цельнозерновой тост и творог или хумус: больше белка и клетчатки, а перекус — сытнее.',joke:'Вкусно. Сытно. Без диетических драм. 😎'},
  banana:{name:'банан',title:'Бананально,<br>но вкусно!',mood:'Проверь меня: я ещё могу перепутать',kcal:'89',protein:'1,1 г',fat:'0,3 г',carbs:'22,8 г',fiber:'2,6 г',advice:'Банан зовёт компанию',text:'Добавь натуральный йогурт и овсяные хлопья: белок и клетчатка сделают перекус сытнее.',joke:'Жёлтый, весёлый, без сложных манёвров 🍌'},
  orange:{name:'апельсин',title:'Оранжевое<br>настроение!',mood:'Цитрусовый знакомец найден',kcal:'47',protein:'0,9 г',fat:'0,1 г',carbs:'11,8 г',fiber:'2,4 г',advice:'Дольки радости',text:'Добавь апельсин к йогурту без добавленного сахара. Целый фрукт сохраняет больше клетчатки, чем сок.',joke:'Солнечный, но не зазнался 🍊'},
  broccoli:{name:'брокколи',title:'Кудрявый<br>знакомец!',mood:'Проверь меня: я ещё могу перепутать',kcal:'34',protein:'2,8 г',fat:'0,4 г',carbs:'6,6 г',fiber:'2,6 г',advice:'Зелёная компания',text:'Приготовь на пару и добавь к крупе и рыбе или фасоли. Получится разнообразный обед.',joke:'Маленькое деревце, большие планы 🥦'},
  cucumber:{name:'огурец',title:'Хруст — и<br>знакомы!',mood:'Хрустящий знакомец найден',kcal:'15',protein:'0,7 г',fat:'0,1 г',carbs:'3,6 г',fiber:'0,5 г',advice:'Хрустящий перекус',text:'Огурец, хумус и цельнозерновой хлеб — простой перекус с белком и клетчаткой.',joke:'Хрустит громче, чем рассказывает 🥒'},
  pepper:{name:'сладкий перец',title:'Перчик,<br>но не острый!',mood:'Цветной знакомец найден',kcal:'31',protein:'1,0 г',fat:'0,3 г',carbs:'6,0 г',fiber:'2,1 г',advice:'Добавим цвета',text:'Нарежь перец полосками и подай с хумусом. Или добавь к салату с фасолью.',joke:'Красивый, сочный, без драмы 🌶️'}
};
function show(id){document.querySelectorAll('.screen').forEach(x=>x.classList.toggle('active',x.id===id))}
function toast(text){const t=$('#toast');t.textContent=text;t.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>t.classList.remove('show'),3500)}
function stopCamera(){if(stream){stream.getTracks().forEach(t=>t.stop());stream=null}$('#cameraWindow')?.classList.remove('live')}
function closeAll(){requestId++;clearTimeout(scanTimer);clearInterval(analysisTimer);stopCamera();show('welcomeScreen')}
async function openCamera(){
 const id=++requestId; stopCamera(); show('cameraScreen'); $('#recognize').disabled=true;
 const heading=document.querySelector('.camera-empty b'), note=document.querySelector('.camera-empty span');
 heading.textContent='Камера готовится'; note.textContent='Разреши доступ и покажи один продукт';
 try{
  if(!navigator.mediaDevices?.getUserMedia)throw Error('secure');
  const incoming=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'}},audio:false});
  if(id!==requestId){incoming.getTracks().forEach(t=>t.stop());return;}
  stream=incoming;$('#video').srcObject=stream;await $('#video').play();
  if(id!==requestId)return;
  $('#cameraWindow').classList.add('live');$('#recognize').disabled=false;
 }catch(e){if(id!==requestId)return;stopCamera();heading.textContent='Камера не открылась';
  note.textContent=!window.isSecureContext?'Для камеры нужен HTTPS или localhost. Можно выбрать фото ниже.':e.name==='NotAllowedError'?'Разреши камеру в настройках браузера или выбери фото ниже.':'Проверь камеру или выбери фото ниже.';
 }
}
function withTimeout(p,ms){return new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(Error('timeout')),ms);p.then(value=>{clearTimeout(timer);resolve(value);},error=>{clearTimeout(timer);reject(error);});});}
function beginAnalysis(image){const id=++requestId;stopCamera();show('analysisScreen');const title=$('#analysisTitle'),sub=$('#analysisSubtitle'),joke=$('#analysisJoke');let n=0;const texts=[['Разглядываю. Я пока маленький…','томатчик сверяет продукт, калории и БЖУ','Большое старание в маленьком пакетике 💚'],['Листаю свою вкусную энциклопедию…','Ищу знакомые очертания и цвет','Носик говорит: почти узнал!'],['Могу перепутать. Проверим вместе?','Ещё секундочку — я очень стараюсь','Не подглядываем 👀']];function change(){const x=texts[Math.min(n++,2)];title.textContent=x[0];sub.textContent=x[1];joke.textContent=x[2]}change();analysisTimer=setInterval(change,2500);scanTimer=setTimeout(async()=>{clearInterval(analysisTimer);let result=null;try{if(!window.mobilenet)throw Error();model=model||await withTimeout(mobilenet.load({version:2,alpha:1}),30000);const predictions=await withTimeout(model.classify(image,5),15000);const label=(predictions[0]?.className||'').toLowerCase();if(predictions[0]?.probability>=.65){if(label.includes('banana'))result='banana';else if(label.includes('orange'))result='orange';else if(label.includes('broccoli'))result='broccoli';else if(label.includes('cucumber'))result='cucumber';else if(label.includes('bell pepper')||label.includes('pepper'))result='pepper';else if(label.includes('tomato'))result='tomato'}}catch(e){}if(id===requestId)renderResult(result)},7500)}
function renderResult(key){show('resultScreen');const f=foods[key];$('#nutrition').hidden=!f;$('#resultStatus').textContent=f?'● Похоже, это '+f.name:'● Пока не узнал продукт';$('#resultTitle').innerHTML=f?f.title:'Ой. Я ещё росточек!';$('#resultMood').textContent=f?f.mood:'Не буду придумывать БЖУ';if(f){$('#kcal').textContent=f.kcal;$('#protein').textContent=f.protein;$('#fat').textContent=f.fat;$('#carbs').textContent=f.carbs;$('#fiber').textContent=f.fiber;$('#nutritionNote').textContent='≈ Средние значения для продукта'}$('#adviceEyebrow').textContent=f?'ИДЕЯ ДЛЯ ПЕРЕКУСА':'МАСКОТ ЕЩЁ УЧИТСЯ';$('#adviceTitle').textContent=f?f.advice:'Знаю пока не всё';$('#adviceText').textContent=f?f.text:'Это может быть незнакомая еда, не еда или просто сложный ракурс. Покажи один продукт крупнее — попробую ещё раз.';$('#adviceJoke').textContent=f?f.joke:'Заглядывай ещё — будем знакомиться с продуктами вместе!';$('#giftTitle').textContent=f?'Совет — тебе. Обнимашки — мне!':'Я ещё росточек. Не сердись 💚';$('#giftText').textContent='За терпение — загляни за бонусом в приложение';}
function capture(){const v=$('#video');if(!v.videoWidth)return toast('Камера ещё готовится — секундочку');const c=document.createElement('canvas');c.width=640;c.height=Math.round(v.videoHeight/v.videoWidth*640);c.getContext('2d').drawImage(v,0,0,c.width,c.height);beginAnalysis(c)}
function photo(e){const file=e.target.files?.[0];if(!file)return;const url=URL.createObjectURL(file),img=new Image();img.onload=()=>{beginAnalysis(img);URL.revokeObjectURL(url)};img.onerror=()=>{URL.revokeObjectURL(url);toast('Не удалось прочитать это фото. Попробуй ещё раз.')};img.src=url;e.target.value=''}
document.addEventListener('DOMContentLoaded',()=>{$('#openCamera').onclick=openCamera;$('#recognize').onclick=capture;$('#photoInput').onchange=photo;$('#again').onclick=openCamera;document.querySelectorAll('[data-close]').forEach(x=>x.onclick=closeAll);$('#bonus').onclick=()=>{try{location.href='tsxapp://app/personal_offers_list'}catch(e){toast('Переход в персональные предложения доступен в приложении 💚')}}});window.addEventListener('pagehide',stopCamera);
