const $=s=>document.querySelector(s);
let stream=null,analysisTimer=null,scanTimer=null,model=null,requestId=0;
const foods={
 tomato:{name:'помидор',title:'Кажется,<br>у нас томатч!',mood:'Проверь меня: я ещё могу перепутать',kcal:'18',protein:'0,9 г',fat:'0,2 г',carbs:'3,9 г',fiber:'1,2 г',advice:'Томат ищет компанию',text:'Добавь цельнозерновой тост и творог или хумус: больше белка и клетчатки, а перекус — сытнее.',joke:'Вкусно. Сытно. Без диетических драм. 😎'},
 banana:{name:'банан',title:'Бананально,<br>но вкусно!',mood:'Жёлтый знакомец найден',kcal:'89',protein:'1,1 г',fat:'0,3 г',carbs:'22,8 г',fiber:'2,6 г',advice:'Банан зовёт компанию',text:'Добавь натуральный йогурт и овсяные хлопья: белок и клетчатка сделают перекус сытнее.',joke:'Жёлтый, весёлый, без сложных манёвров 🍌'},
 apple:{name:'яблоко',title:'Яблочко,<br>это точно!',mood:'Хрустящий знакомец найден',kcal:'52',protein:'0,3 г',fat:'0,2 г',carbs:'13,8 г',fiber:'2,4 г',advice:'Яблоко просит пару',text:'Добавь йогурт, творог или горсть орехов: так фруктовый перекус будет сытнее.',joke:'Хрустит — значит, всё идёт по плану 🍎'},
 orange:{name:'апельсин',title:'Оранжевое<br>настроение!',mood:'Цитрусовый знакомец найден',kcal:'47',protein:'0,9 г',fat:'0,1 г',carbs:'11,8 г',fiber:'2,4 г',advice:'Дольки радости',text:'Съешь целый апельсин с йогуртом без добавленного сахара. Так останется больше клетчатки, чем в соке.',joke:'Солнечный, но не зазнался 🍊'},
 strawberry:{name:'клубника',title:'Клубничный<br>знак!',mood:'Ягодный знакомец найден',kcal:'32',protein:'0,7 г',fat:'0,3 г',carbs:'7,7 г',fiber:'2,0 г',advice:'Ягодная компания',text:'Смешай клубнику с творогом или натуральным йогуртом — получится лёгкий перекус с белком.',joke:'Маленькая ягода, большое настроение 🍓'},
 lemon:{name:'лимон',title:'Кислинка,<br>но полезная!',mood:'Цитрусовый знакомец найден',kcal:'29',protein:'1,1 г',fat:'0,3 г',carbs:'9,3 г',fiber:'2,8 г',advice:'Лимон — в команду',text:'Используй лимон для вкуса в салате, рыбе или воде, но не считай его самостоятельным перекусом.',joke:'Скулы свело, зато вкусно 🍋'},
 pineapple:{name:'ананас',title:'Ананасовый<br>привет!',mood:'Тропический знакомец найден',kcal:'50',protein:'0,5 г',fat:'0,1 г',carbs:'13,1 г',fiber:'1,4 г',advice:'Тропики к йогурту',text:'Добавь ананас к творогу или натуральному йогурту и выбирай фрукт без сиропа.',joke:'Отпуск, который помещается в тарелку 🍍'},
 pomegranate:{name:'гранат',title:'Зернистый<br>знакомец!',mood:'Фрукт найден',kcal:'83',protein:'1,7 г',fat:'1,2 г',carbs:'18,7 г',fiber:'4,0 г',advice:'Зёрна в пару',text:'Посыпь зёрнами салат или йогурт. Добавь источник белка, чтобы перекус был плотнее.',joke:'Каждое зёрнышко — маленький сюрприз ❤️'},
 broccoli:{name:'брокколи',title:'Кудрявый<br>знакомец!',mood:'Зелёный знакомец найден',kcal:'34',protein:'2,8 г',fat:'0,4 г',carbs:'6,6 г',fiber:'2,6 г',advice:'Зелёная компания',text:'Приготовь брокколи на пару и добавь к крупе, рыбе или фасоли — получится разнообразный обед.',joke:'Маленькое деревце, большие планы 🥦'},
 cauliflower:{name:'цветная капуста',title:'Цветной<br>знакомец!',mood:'Овощ найден',kcal:'25',protein:'1,9 г',fat:'0,3 г',carbs:'5,0 г',fiber:'2,0 г',advice:'Капуста не скучная',text:'Запеки с пряностями и подай с яйцом, рыбой или бобовыми — будет и вкус, и сытость.',joke:'Белая, но с характером'},
 cucumber:{name:'огурец',title:'Хруст — и<br>знакомы!',mood:'Хрустящий знакомец найден',kcal:'15',protein:'0,7 г',fat:'0,1 г',carbs:'3,6 г',fiber:'0,5 г',advice:'Хрустящий перекус',text:'Огурец, хумус и цельнозерновой хлеб — простой перекус с белком и клетчаткой.',joke:'Хрустит громче, чем рассказывает 🥒'},
 pepper:{name:'сладкий перец',title:'Перчик,<br>но не острый!',mood:'Цветной знакомец найден',kcal:'31',protein:'1,0 г',fat:'0,3 г',carbs:'6,0 г',fiber:'2,1 г',advice:'Добавим цвета',text:'Нарежь перец полосками и подай с хумусом или добавь к салату с фасолью.',joke:'Красивый, сочный, без драмы 🌶️'},
 carrot:{name:'морковь',title:'Морковный<br>знак!',mood:'Овощ найден',kcal:'41',protein:'0,9 г',fat:'0,2 г',carbs:'9,6 г',fiber:'2,8 г',advice:'Морковь ищет хумус',text:'Нарежь морковь палочками и добавь хумус или йогуртовый соус.',joke:'Оранжевый хруст для настроения 🥕'},
 potato:{name:'картофель',title:'Картофельный<br>знакомец!',mood:'Овощ найден',kcal:'77',protein:'2,0 г',fat:'0,1 г',carbs:'17,5 г',fiber:'2,2 г',advice:'Картофель — не один',text:'Запеки картофель и добавь белок: яйцо, фасоль, рыбу или творог. Так будет сытнее.',joke:'Главное — не превращать всё в драму с фритюром'},
 mushroom:{name:'грибы',title:'Грибной<br>знакомец!',mood:'Овощной отдел одобряет',kcal:'22',protein:'3,1 г',fat:'0,3 г',carbs:'3,3 г',fiber:'1,0 г',advice:'Грибы к омлету',text:'Добавь грибы к яйцам, крупе или фасоли. Они дают вкус и объём блюду.',joke:'Лесной, но уже на кухне 🍄'},
 corn:{name:'кукуруза',title:'Кукурузный<br>знак!',mood:'Зерновой знакомец найден',kcal:'86',protein:'3,3 г',fat:'1,4 г',carbs:'19,0 г',fiber:'2,7 г',advice:'Кукуруза в салат',text:'Добавь кукурузу к фасоли и овощам. Для полноценности можно добавить яйцо или сыр.',joke:'Зёрнышко к зёрнышку — и готово 🌽'},
 egg:{name:'яйцо',title:'Яичный<br>знакомец!',mood:'Белковый продукт найден',kcal:'143',protein:'12,6 г',fat:'9,5 г',carbs:'0,7 г',fiber:'0 г',advice:'Яйцо любит овощи',text:'Добавь овощи и кусочек цельнозернового хлеба — получится простой сытный приём пищи.',joke:'Белок без лишних разговоров 🥚'},
 bread:{name:'хлеб',title:'Хлебный<br>знак!',mood:'Похоже на хлеб',kcal:'247',protein:'8,7 г',fat:'3,4 г',carbs:'41,0 г',fiber:'6,0 г',advice:'Хлебу нужен напарник',text:'Выбирай цельнозерновой хлеб и добавь белок: творог, яйцо, сыр или хумус.',joke:'Тост — это тоже план'},
 cheese:{name:'сыр',title:'Сырный<br>знакомец!',mood:'Похоже на сыр',kcal:'350',protein:'25,0 г',fat:'27,0 г',carbs:'1,3 г',fiber:'0 г',advice:'Сыр и свежий хруст',text:'Добавь к сыру овощи и цельнозерновой хлеб. Так порция будет разнообразнее.',joke:'Тянет не только сыр, но и настроение 🧀'},
 pizza:{name:'пицца',title:'Пицца —<br>это знак!',mood:'Похоже на пиццу',kcal:'266',protein:'11,0 г',fat:'10,0 г',carbs:'33,0 г',fiber:'2,3 г',advice:'Пицце — овощную компанию',text:'Добавь салат или овощи рядом и выбери воду. Не запрещаем вкусное — собираем тарелку разнообразнее.',joke:'Круглая, вкусная, без диетических драм 🍕'},
 burger:{name:'бургер',title:'Бургер<br>на связи!',mood:'Похоже на бургер',kcal:'295',protein:'17,0 г',fat:'14,0 г',carbs:'27,0 г',fiber:'2,0 г',advice:'Бургеру — овощи',text:'Добавь овощи и воду, а картофель можно разделить или заменить салатом.',joke:'Иногда хочется булочку. Это нормально 🍔'},
 coffee:{name:'кофе',title:'Кофейный<br>знак!',mood:'Похоже на кофе',kcal:'2',protein:'0,3 г',fat:'0 г',carbs:'0 г',fiber:'0 г',advice:'Кофе ищет компанию',text:'Если это перекус, добавь к кофе йогурт, фрукт или бутерброд с белком.',joke:'Бодрит без лишних обещаний ☕'},
 icecream:{name:'мороженое',title:'Холодный<br>знакомец!',mood:'Похоже на мороженое',kcal:'207',protein:'3,5 г',fat:'11,0 г',carbs:'24,0 г',fiber:'0 г',advice:'Мороженому — не драма',text:'Съешь порцию с удовольствием. Если хочется сытости, добавь фрукт или полноценный приём пищи.',joke:'Холодно, сладко, всё по-честному 🍦'}
};
const rules=[['banana','banana'],['granny smith','apple'],['apple','apple'],['orange','orange'],['strawberry','strawberry'],['lemon','lemon'],['pineapple','pineapple'],['pomegranate','pomegranate'],['broccoli','broccoli'],['cauliflower','cauliflower'],['cucumber','cucumber'],['zucchini','cucumber'],['bell pepper','pepper'],['pepper','pepper'],['carrot','carrot'],['potato','potato'],['mushroom','mushroom'],['corn','corn'],['ear of corn','corn'],['egg','egg'],['omelet','egg'],['bread','bread'],['bagel','bread'],['toast','bread'],['cheese','cheese'],['pizza','pizza'],['cheeseburger','burger'],['burger','burger'],['hamburger','burger'],['espresso','coffee'],['coffee','coffee'],['ice cream','icecream'],['icecream','icecream'],['tomato','tomato']];
function show(id){document.querySelectorAll('.screen').forEach(x=>x.classList.toggle('active',x.id===id))}
function toast(text){const t=$('#toast');t.textContent=text;t.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>t.classList.remove('show'),3800)}
function stopCamera(){if(stream){stream.getTracks().forEach(t=>t.stop());stream=null}$('#cameraWindow')?.classList.remove('live')}
function closeAll(){requestId++;clearTimeout(scanTimer);clearInterval(analysisTimer);stopCamera();show('welcomeScreen')}
async function openCamera(){const id=++requestId;stopCamera();show('cameraScreen');$('#recognize').disabled=true;const heading=$('.camera-empty b'),note=$('.camera-empty span');heading.textContent='Камера готовится';note.textContent='Разреши доступ и покажи один продукт';try{if(!navigator.mediaDevices?.getUserMedia)throw Error('secure');const incoming=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'}},audio:false});if(id!==requestId){incoming.getTracks().forEach(t=>t.stop());return}stream=incoming;$('#video').srcObject=stream;await $('#video').play();if(id!==requestId)return;$('#cameraWindow').classList.add('live');$('#recognize').disabled=false}catch(e){if(id!==requestId)return;heading.textContent='Камера не открылась';note.textContent=!window.isSecureContext?'Для камеры нужен HTTPS или localhost. Можно выбрать фото ниже.':e.name==='NotAllowedError'?'Разреши камеру в настройках браузера или выбери фото ниже.':'Проверь камеру или выбери фото ниже.'}}
function withTimeout(p,ms){return new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(Error('timeout')),ms);p.then(v=>{clearTimeout(timer);resolve(v)},e=>{clearTimeout(timer);reject(e)})})}
async function classify(source){try{if(!window.mobilenet)throw Error('model');model=model||await withTimeout(mobilenet.load({version:2,alpha:1}),30000);const predictions=await withTimeout(model.classify(source,10),15000);for(const p of predictions){const label=(p.className||'').toLowerCase();const found=rules.find(([part])=>label.includes(part));if(found&&p.probability>=.12)return found[1]} }catch(e){console.warn('Tomatchik classifier:',e)}return null}
function beginAnalysis(source){const id=++requestId;stopCamera();show('analysisScreen');const title=$('#analysisTitle'),sub=$('#analysisSubtitle'),joke=$('#analysisJoke');let n=0;const phrases=[['Проверяю продукт…','Томатчик сравнивает форму, цвет и детали','Ещё секундочку — хочу дать точный совет 💚'],['Сверяю с вкусной энциклопедией…','Ищу подходящий состав и БЖУ','Носик почти определился 👀'],['Готовлю результат…','Подбираю идею, с чем это съесть','Без диетических драм — только полезные подсказки']];const change=()=>{const x=phrases[Math.min(n++,phrases.length-1)];title.textContent=x[0];sub.textContent=x[1];joke.textContent=x[2]};change();analysisTimer=setInterval(change,1700);scanTimer=setTimeout(async()=>{clearInterval(analysisTimer);const result=await classify(source);if(id===requestId)renderResult(result)},5600)}
function renderResult(key){show('resultScreen');const f=foods[key];$('#nutrition').hidden=!f;$('#resultStatus').textContent=f?'● Похоже, это '+f.name:'● Пока не получилось уверенно определить';$('#resultTitle').innerHTML=f?f.title:'Давай попробуем ещё раз';$('#resultMood').textContent=f?f.mood:'Не буду придумывать продукт и БЖУ';if(f){$('#kcal').textContent=f.kcal;$('#protein').textContent=f.protein;$('#fat').textContent=f.fat;$('#carbs').textContent=f.carbs;$('#fiber').textContent=f.fiber;$('#nutritionNote').textContent='≈ Средние значения для продукта'}$('#adviceEyebrow').textContent=f?'ИДЕЯ ДЛЯ ПЕРЕКУСА':'ТОМАТЧИК ЕЩЁ УЧИТСЯ';$('#adviceTitle').textContent=f?f.advice:'Покажи продукт чуть крупнее';$('#adviceText').textContent=f?f.text:'Лучше всего он узнаёт отдельные фрукты, овощи, хлеб, сыр, яйца, кофе и готовые блюда вроде пиццы. Если на фото упаковка или несколько предметов, попробуй один продукт крупным планом.';$('#adviceJoke').textContent=f?f.joke:'Я не буду угадывать наобум — попробуем ещё раз!';$('#giftTitle').textContent='Если я ошибся — не обижайся!';$('#giftText').textContent='Ты помог Томатчику стать умнее — держи подарок 🎁'}
function capture(){const v=$('#video');if(!v.videoWidth)return toast('Камера ещё готовится — секундочку');const c=document.createElement('canvas');c.width=640;c.height=Math.round(v.videoHeight/v.videoWidth*640);c.getContext('2d').drawImage(v,0,0,c.width,c.height);beginAnalysis(c)}
function photo(e){const file=e.target.files?.[0];if(!file)return;const url=URL.createObjectURL(file),img=new Image();img.onload=()=>{beginAnalysis(img);URL.revokeObjectURL(url)};img.onerror=()=>{URL.revokeObjectURL(url);toast('Не удалось прочитать это фото. Попробуй ещё раз.')};img.src=url;e.target.value=''}
document.addEventListener('DOMContentLoaded',()=>{$('#openCamera').onclick=openCamera;$('#recognize').onclick=capture;$('#photoInput').onchange=photo;$('#again').onclick=openCamera;document.querySelectorAll('[data-close]').forEach(x=>x.onclick=closeAll);$('#bonus').onclick=()=>{try{location.href='tsxapp://app/personal_offers_list'}catch(e){toast('Персональные предложения доступны в приложении 💚')}}});window.addEventListener('pagehide',stopCamera);
